# Generated by Django 6.0 on 2025-12-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="professor_images/"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("sub", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=30)),
                ("roll_number", models.CharField(max_length=7, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="FieldProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("submited_by_roll", models.CharField(max_length=7, unique=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("project_file", models.FileField(upload_to="fild_projects")),
                ("is_checked", models.BooleanField(default=False)),
                ("marks", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_opst.student",
                    ),
                ),
            ],
        ),
    ]
