# Generated by Django 6.0 on 2026-02-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_opst", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldproject",
            name="submited_by_roll",
        ),
        migrations.AlterField(
            model_name="fieldproject",
            name="marks",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
